name: Build

on: push

jobs:
  build:
    runs-on: Ubuntu 22.04.2 LTS

    steps:
      - uses: actions/checkout@v2

      - name: Check codestyle
        run: git ls-files *.{c,h} | xargs clang-format -i --verbose && git diff --exit-code

      - name: Build application
        run: makes